- name: Install redis repos
  ansible.builtin.yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    state: present

- name: Install Redis
  ansible.builtin.yum:
    name: redis
    enablerepo: remi

- name: Update Redis Config Listen address
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start the Redis
  ansible.builtin.systemd_service:
    state: started
    name: redis
    enabled: true
