- name: Install Redis Repo
  ansible.builtin.shell:
    cmd: dnf install https://rpms.remirepo.net/enterprise/remi-release-8.rpm -y

- name: Enable Redis Remi
  ansible.builtin.shell:
    cmd: dnf module enable redis:remi-6.2 -y

- name: Install Redis
  ansible.builtin.shell:
    cmd: dnf install redis -y