- name: Install redis repos
  ansible.builtin.yum:
    name: http://rpms.remirepo.net/enterprise/remi-release-6.rpm
    state: present

- name: Install redis
  ansible.builtin.yum:
    name: redis
    enablerepo: remi

- name: Update Redis Listen address
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start redis
  ansible.builtin.systemd_service:
    name: redis
    state: restarted
    enabled: yes
