- name: Install Maven
  ansible.builtin.dnf:
    name: maven
    state: latest

- name: Add Roboshop User
  ansible.builtin.user:
    name: roboshop

- name: Create Directory App
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download App Code
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/shipping.zip
    dest: /app
    remote_src: yes
