- name: Install Maven
  ansible.builtin.dnf:
    name: maven
    state: latest

- name: Add Roboshop User
  ansible.builtin.user:
    name: roboshop

- name: Create Directory App
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download App Code
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/shipping.zip
    dest: /app
    remote_src: yes

- name: Make maven package
  ansible.builtin.shell:
    cmd: mvn clean package && mv target/shipping-1.0.jar shipping.jar
    chdir: /app

- name: Update systemd file
  template:
    src: systemd.service
    dest: /etc/systemd/system/shipping.service

- name: Install MySQL
  ansible.builtin.dnf:
    name: mysql
    state: present


- name: Start Shipping Service
  systemd:
    name: shipping
    state: restarted
    enabled: yes
    daemon_reload: yes
