- name: Install Maven
  ansible.builtin.yum:
    name: maven
    state: present

- name: Add Roboshop User
  ansible.builtin.user:
    name: roboshop

- name: Download Htdocs Content
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Copy the Content
  ansible.builtin.copy:
    src: /tmp/shipping-main
    dest: /tmp/shipping
    become_user: roboshop
    remote_src: yes

- name: MVN Clean Package
  ansible.builtin.shell:
  cmd: mvn clean package
  become_user: roboshop

- name: Copy the Content
  ansible.builtin.copy:
    src: /shipping/target/shipping-1.0.jar
    dest: /shipping/shipping.jar
    become_user: roboshop

