
#  # useradd roboshop
#Download the repo
#$ cd /home/roboshop
#$ curl -s -L -o /tmp/shipping.zip "https://github.com/roboshop-devops-project/shipping/archive/main.zip"
#$ unzip /tmp/shipping.zip
#$ mv shipping-main shipping
#$ cd shipping
#$ mvn clean package
#$ mv target/shipping-1.0.jar shipping.jar
#Update Servers IP address in /home/roboshop/shipping/systemd.service
#
#Copy the service file and start the service.
#
## mv /home/roboshop/shipping/systemd.service /etc/systemd/system/shipping.service
## systemctl daemon-reload
## systemctl start shipping
## systemctl enable shipping
- name: Install Maven
  ansible.builtin.yum:
    name: maven
    state: present

- name: Add Roboshop User
  ansible.builtin.user:
    name: roboshop

- name: Download Htdocs Content
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Copy the Content
  ansible.builtin.copy:
    src: /tmp/shipping-main
    dest: /tmp/shipping
    become_user: roboshop
    remote_src: yes

- name: MVN Clean Package
  ansible.builtin.shell:
  cmd: mvn clean package
  become_user: roboshop

- name: Copy the Content
  ansible.builtin.copy:
    src: /shipping/target/shipping-1.0.jar
    dest: /shipping/shipping.jar
    become_user: roboshop

