- name: Setup Frontend
  hosts: frontend
  tags: frontend
  become: true
  roles:
    - frontend

- name: Setup Mongodb
  hosts: mongodb
  tags: mongodb
  become: true
  roles:
    - mongodb

- name: Setup Catalogue
  hosts: catalogue
  tags: catalogue
  become: true
  roles:
    - catalogue

- name: Setup Redis
  hosts: redis
  tags: redis
  become: true
  roles:
    - redis

- name: Setup User
  hosts: user
  tags: user
  become: true
  roles:
    - user

- name: Setup Cart
  hosts: cart
  tags: cart
  become: true
  roles:
    - cart