- name: Setup Frontend
  hosts: frontend
  tags: frontend
  become: true
  roles:
    - frontend

- name: Setup Mongodb
  hosts: mongodb
  tags: mongodb
  become: true
  roles:
    - mongodb

- name: Setup Catalogue
  hosts: catalogue
  tags: catalogue
  become: true
  roles:
    - catalogue