- name: Install Pyhton
  ansible.builtin.dnf:
    name:
      - python36
      - gcc
      - python3-devel
    state: latest

- name: Add Roboshop User
  ansible.builtin.user:
    name: roboshop

- name: Create Directory App
  ansible.builtin.file:
    path: /app
    state: directory

- name: Download App Code
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/payment.zip
    dest: /app
    remote_src: yes

- name: Download App Component
  ansible.builtin.get_url:
    url: http://172.31.35.162:8081/repository/{{COMPONENT}}/{{COMPONENT}}-{{APP_VERSION}}.zip
    dest: /tmp/{{COMPONENT}}.zip
    url_username: "{{NEXUS_USER}}"
    url_password: "{{NEXUS_PASS}}"
    when: APP_VERSION != ""

- name: Extract App Code
  ansible.builtin.unarchive:
    src: /tmp/{{COMPONENT}}.zip
    dest: /app
    remote_src: yes
    when: APP_VERSION != ""

- name: Install Python Dependencies
  ansible.builtin.pip:
    requirements: "/app/requirements.txt"
    executable: pip3.6

- name: Update systemd file
  template:
    src: systemd.service
    dest: /etc/systemd/system/payment.service

- name: Start Payment Service
  systemd:
    name: payment
    state: restarted
    enabled: yes
    daemon_reload: yes