- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest

- name: Start Nginx Service
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    enabled: yes

- name: Remove Old Content
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent
