- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: latest


- name: Remove Old Content
  ansible.builtin.file:
    path: /usr/share/nginx/html/
    state: absent

- name: Download Frontend Component
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /tmp
    remote_src: yes

- name: Copy Htdocs content
  ansible.builtin.copy:
    src: /tmp/
    dest: /usr/share/nginx/html/
    remote_src: yes

- name: Start Nginx Service
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    enabled: yes
