- name: Disable MySQl Default Version
  ansible.builtin.shell:
    cmd: dnf module disable mysql -y

- name: Copy Mongodb repo File
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: Install MySQL
  ansible.builtin.shell:
    cmd: dnf install mysql-community-server -y