- name: Disable default nodejs
  ansible.builtin.shell:
    cmd: dnf module disable nodejs -y

- name: Enable nodejs version18
  ansible.builtin.shell:
    cmd: dnf module enable nodejs:18 -y

- name: Install Nodejs Package
  ansible.builtin.shell:
    cmd: dnf install nodejs -y