- name: Disable nodejs Default Version
  ansible.builtin.dnf:
    name: nodejs
    state: absent

- name: Enable nodejs18 Version
  ansible.builtin.dnf:
    name: nodejs:18
    state: present

- name: Install nodejs18 Version
  ansible.builtin.dnf:
    name: nodejs
    state: present