- name: copy Prometheus Config
  template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Restart Prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted

- name: Copy Alert Manager Config
  template:
    src: alertmanager.yml
    dest: /opt/alertmanager/alertmanager.yml

- name: Restart alertmanager
  systemd:
    name: alertmanager
    state: restarted