#$ mvn clean package
#$ mv target/shipping-1.0.jar shipping.jar
#Update Servers IP address in /home/roboshop/shipping/systemd.service
#
#Copy the service file and start the service.

# mv /home/roboshop/shipping/systemd.service /etc/systemd/system/shipping.service
# systemctl daemon-reload
# systemctl start shipping
# systemctl enable shipping
- name: Install Maven
  yum:
    name: maven
    state: present

- name: Downlad code
  include_role:
    name: common
    tasks_from: download
  vars:
    APP_LOCATION: "/home/roboshop/{{COMPONENT}}"
    APP_USER: roboshop

- name: Make maven package
  ansible.builtin.shell:
    cmd: mvn clean package && mv target/shipping-1.0.jar shipping.jar
    chdir: "/home/roboshop/{{COMPONENT}}"
  become_user: roboshop

- name: Downlad Systemd
  include_role:
    name: common
    tasks_from: systemd



