- name: Install nodejs
  yum:
    name: ["nodejs","make","gcc-c++"]
    state: present

- name: Add Roboshop app user
  user:
    name: roboshop

- name: Downlad code
  include_role:
    name: common
    tasks_from: download

- name: Remove existing data
  file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: Copy app code
  copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}
    remote_src: true
  become_user: roboshop

- name: Install Nodejs Dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}

- name: Update systemd file
  template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Start {{COMPONENT}} service
  systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon_reload: yes