- name: Install nodejs
  yum:
    name: ["nodejs","make","gcc-c++"]
    state: present

- name: Downlad code
  include_role:
    name: common
    tasks_from: download
  vars:
    APP_LOCATION: "/home/roboshop/{{COMPONENT}}"
    APP_USER: roboshop

- name: Install Nodejs Dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}

- name: Downlad Systemd
  include_role:
    name: common
    tasks_from: systemd

