- name: Install nodejs
  yum:
    name: ["nodejs","make","gcc-c++"]
    state: present

- name: Downlad code
  include_role:
    name: common
    tasks_from: download
  vars:
    APP_LOCATION: "/home/roboshop/{{COMPONENT}}"

- name: Install Nodejs Dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}

- name: Update systemd file
  template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Start {{COMPONENT}} service
  systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon_reload: yes